stages:
  - mirror
  - test
  - deploy
  - wiki

mirror_master:
  stage: mirror
  only:
    - master
  script:
    #- git push -u git@gitlab.com:namboy94/gfworks.git --all
    - git push -u git@github.com:namboy94/gfworks.git --all
    #- git push -u git@bitbucket.org:namboy94/gfworks.git --all

run_unit_tests:
  stage: test
  only:
    - master
    - develop
  script:
    - python3 setup.py test

upload_to_pypi:
  stage: deploy
  only:
    - master
  script:
    - python3 setup.py register sdist upload
  allow_failure: true

generate_statistics:
  stage: wiki
  only:
    - master
  script:
    - gitstats . git_stats
    - cd doc
    - make clean
    - make buildsource
    - make html
    - cd ..

    - git clone git@gitlab.namibsun.net:namboy94/gfworks.wiki.git
    - cd gfworks.wiki
    - rm -rf git_stats html
    - mv ../git_stats .
    - mv ../doc/build/html .
    - git add --all
    - git commit -m "Updated Documentation and Statistics"
    - git push -u origin master
