stages:
  - setup
  - test
  - upload
  - cleanup
  - upgrade

clone_master:
  stage: setup
  script:
    - cd
    - git clone http://gitlab.namibsun.net/namboy94/gfworks.git
    - cd gfworks
    - git push -u git@gitlab.com:namboy94/gfworks.git --all
    - git push -u git@github.com:namboy94/gfworks.git --all
    - git push -u git@bitbucket.org:namboy94/gfworks.git --all

run_unit_tests:
  stage: test
  script:
    - cd
    - cd gfworks
    - python setup.py test

generate_statistics:
  stage: test
  script:
    - cd
    - cd gfworks
    - git_stats generate

upload_to_pypi:
  stage: upload
  script:
    - cd
    - cd gfworks
    - python setup.py register sdist upload
    - sleep 60
  allow_failure: true

upload_statistics:
  stage: upload
  script:
    - cd
    - cd gfworks
    - rsync -avP --delete-after git_stats/ www.krumreyh.de@ssh.strato.de:~/git_stats_pages/gfworks
    - ssh www.krumreyh.de@ssh.strato.de 'rsync -av --delete-after git_stats_pages Homepage/'


delete_clone:
  stage: cleanup
  script:
    - cd
    - rm -rf gfworks
